### PR TITLE
Update ShapeRecord.php

### PR DESCRIPTION
**Pull request by coreation**

### CODE REVIEW

**Comment by muka** [comment]
Seems `parts` became `points` for some reason. Let's blame someone :)
I'll review the code and merge this, Thanks

**Comment by coreation** [comment]
The ESRI is quite deterministic, but in code indeed somewhere along the line....we can blame someone. Prepare the fire ;).

**Comment by coreation** [comment]
Hey @muka do I need write a unittest or will you merge this with master? :)

**Comment by muka** [comment]
Updated, would be awesome if you would add a few test :)
Thanks!

**Comment by coreation** [comment]
I think I can, I have some shp files that cover most shape types, point, multipointz, pointz, etc. If something fails I'll make sure to notify you!

**Comment by muka** [comment]
Great, thank you

**Pull request merged**
